#!/usr/bin/env python3
"""Tests for scripts/friction-report.py.

Run with: python3 -m unittest discover tests
     or:  python3 tests/test_friction_report.py

The friction report is a read-only analyzer over the decisions Claude Code
persists in ~/.claude/projects/**/*.jsonl. These tests build synthetic
transcript files (attachment records + matching Bash tool_use blocks) and assert
the report's categorization, target extraction, and joins — never touching a real
transcript.

Signature fidelity: the reason fixtures are generated by calling
bash-foreground-guard.py's own finding builders (not hand-copied strings), so a
change to the guard's wording that broke a category regex fails these tests
instead of silently mis-bucketing real prompts.

Fixture rule (same as test_foreground_guard.py): synthetic commands only.
"""
import datetime as dt
import io
import json
import os
import subprocess
import sys
import tempfile
import unittest
from contextlib import redirect_stdout
from importlib import util
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SCRIPT = REPO / "scripts" / "friction-report.py"
GUARD = REPO / "scripts" / "bash-foreground-guard.py"

# Filenames have dashes, so import by path.
_spec = util.spec_from_file_location("friction_report", SCRIPT)
fr = util.module_from_spec(_spec)
_spec.loader.exec_module(fr)

_gspec = util.spec_from_file_location("foreground_guard", GUARD)
guard = util.module_from_spec(_gspec)
_gspec.loader.exec_module(guard)


# Real reason strings, generated by the guard's own finding builders — one per
# category. Minimal cfg: the builders read only the action keys and hint.
_CFG = {'poll_action': 'ask', 'slow_action': 'ask', 'hint': ''}
REASON_WATCH = guard.finding_watch(
    _CFG, "gh run watch 456", "gh run watch",
    "check once with `gh run view <run-id>`")[1]
REASON_LOOP = guard.finding_loop(_CFG)[1]
REASON_SANDWICH = guard.finding_sandwich(_CFG)[1]
REASON_SLEEP = guard.finding_sleep(_CFG, 300)[1]
REASON_SLOW = guard.finding_slow(
    _CFG, 'the slow-command pattern `make test-race\\b`', 600000, 120000,
    False)[1]
REASON_SLOW_TARGET = guard.finding_slow(
    _CFG, 'the slow-command target `make e2e*`', 1800000, 120000, False)[1]
# The same Class A findings for a `run_in_background: true` call: different
# wording, same categories.
_BG_CFG = dict(_CFG, backgrounded=True)
REASON_BG_WATCH = guard.finding_watch(
    _BG_CFG, "gh run watch 456", "gh run watch",
    "check once with `gh run view <run-id>`")[1]
REASON_BG_LOOP = guard.finding_loop(_BG_CFG)[1]
REASON_BG_SANDWICH = guard.finding_sandwich(_BG_CFG)[1]
REASON_BG_SLEEP = guard.finding_sleep(_BG_CFG, 300)[1]
# The deny->ask override prefix the hook prepends (see bash-foreground-guard.py
# main()); the underlying category must survive it.
REASON_OVERRIDE = ('foreground-guard override acknowledged '
                   '(FOREGROUND_GUARD_OVERRIDE is set) — downgraded from deny '
                   'to a confirmation prompt. ' + REASON_WATCH)
# A sibling guard's override prefix: identical phrasing apart from the guard
# name. In scope under --plugin all, and never a foreground-guard override.
REASON_SIBLING_OVERRIDE = ('prod-guard override acknowledged '
                           '(PROD_GUARD_OVERRIDE is set) — downgraded from deny '
                           'to a confirmation prompt. prod-guard: matches a '
                           'production pattern')


# What a deny actually looks like in a transcript. Claude Code writes no
# attachment for it (issue #25) — the reason reaches the transcript only as the
# error tool result handed back to the agent, so the fixture carries the guard's
# real deny wording: the reason plus the tail main() appends to a deny.
REASON_DENY = REASON_LOOP + " " + guard.deny_tail("auto")


def _deny_record(tooluseid, command, reason=REASON_DENY, cwd="/home/u/proj",
                 ts=None, is_error=True, as_blocks=False):
    """The two records a denied Bash call leaves: the assistant's tool_use and
    the error tool_result carrying the guard's reason. No attachment record —
    that is the bug this recovery exists for."""
    content = ([{"type": "text", "text": reason}] if as_blocks else reason)
    use = {
        "timestamp": ts or "2026-07-01T12:00:00Z",
        "cwd": cwd,
        "message": {"content": [
            {"type": "tool_use", "name": "Bash", "id": tooluseid,
             "input": {"command": command}}]},
    }
    result = {
        "timestamp": ts or "2026-07-01T12:00:00Z",
        "cwd": cwd,
        "message": {"content": [
            {"type": "tool_result", "tool_use_id": tooluseid,
             "is_error": is_error, "content": content}]},
    }
    return use, result


def _decision_record(tooluseid, command, stdout, cwd="/home/u/proj", ts=None,
                     hook_cmd='python3 "/x/scripts/bash-foreground-guard.py"',
                     **att_extra):
    """A transcript attachment record for one hook decision, plus the assistant
    tool_use record that command is joined from. Both carry cwd and timestamp,
    as real records do — the tool_use records are the report's denominator, so
    they meet the same scope filters.

    `type` is `hook_success` unless overridden: every real attachment carries
    one, and only that value means the hook produced a verdict (issue #29)."""
    att = {
        "type": "hook_success",
        "hookName": "PreToolUse:Bash",
        "command": hook_cmd,
        "toolUseID": tooluseid,
        "stdout": stdout,
        "stderr": "",
        "exitCode": 0,
    }
    att.update(att_extra)
    att = {
        "timestamp": ts or "2026-07-01T12:00:00Z",
        "cwd": cwd,
        "attachment": att,
    }
    use = {
        "timestamp": ts or "2026-07-01T12:00:00Z",
        "cwd": cwd,
        "message": {"content": [
            {"type": "tool_use", "name": "Bash", "id": tooluseid,
             "input": {"command": command}}]},
    }
    return use, att


def _crashed_record(tooluseid, command, hook_cmd, **kw):
    """A hook that never ran: Claude Code writes the attachment anyway, with an
    empty stdout, a non-zero exitCode and the failure on stderr. Shape taken
    from the 5,472 real ones behind issue #29 (exit 126, hook script left
    non-executable)."""
    return _decision_record(
        tooluseid, command, "", hook_cmd=hook_cmd,
        type="hook_non_blocking_error", exitCode=126,
        stderr=("Failed with non-blocking status code: /bin/sh: "
                "/x/scripts/run-python-hook.cmd: Permission denied"), **kw)


def _bash_call(tooluseid, command, cwd="/home/u/proj", ts=None):
    """A Bash call the guard deferred on: the tool_use record and nothing else.
    A silent defer writes no attachment (issue #27), so this is the only trace
    such a call leaves — and the whole reason the denominator counts calls."""
    return {
        "timestamp": ts or "2026-07-01T12:00:00Z",
        "cwd": cwd,
        "message": {"content": [
            {"type": "tool_use", "name": "Bash", "id": tooluseid,
             "input": {"command": command}}]},
    }


def _stdout(decision, reason):
    return json.dumps({"hookSpecificOutput": {
        "hookEventName": "PreToolUse",
        "permissionDecision": decision,
        "permissionDecisionReason": reason}})


def write_transcripts(sessions):
    """Write each session (a list of records) as its own .jsonl transcript in a
    fresh temp dir; return the transcript root."""
    root = tempfile.mkdtemp(prefix="fg-guard-friction-")
    proj = os.path.join(root, "-home-u-proj")
    os.makedirs(proj)
    for i, records in enumerate(sessions):
        path = os.path.join(proj, "session%d.jsonl" % i)
        with open(path, "w", encoding="utf-8") as f:
            for rec in records:
                f.write(json.dumps(rec) + "\n")
    return root


def write_transcript(lines):
    """One session's worth of records; see write_transcripts."""
    return write_transcripts([lines])


class ParseSinceTests(unittest.TestCase):
    def test_relative_units(self):
        now = dt.datetime.now(dt.timezone.utc)
        self.assertLess(fr.parse_since("7d"), now)
        self.assertAlmostEqual(
            (now - fr.parse_since("30m")).total_seconds(), 1800, delta=5)

    def test_absolute_date(self):
        self.assertEqual(fr.parse_since("2026-06-01").year, 2026)

    def test_bad_spec_exits(self):
        with self.assertRaises(SystemExit):
            fr.parse_since("banana")

    def test_empty_is_none(self):
        self.assertIsNone(fr.parse_since(None))


class GuardNameTests(unittest.TestCase):
    def test_strips_bash_prefix(self):
        self.assertEqual(
            fr.guard_name('python3 "/x/scripts/bash-foreground-guard.py"'),
            "foreground-guard")

    def test_sibling_guard(self):
        self.assertEqual(
            fr.guard_name('python3 "/x/bash-prod-guard.py"'),
            "prod-guard")

    def test_no_py_is_none(self):
        self.assertIsNone(fr.guard_name("gh run watch 1"))


class CategoryTests(unittest.TestCase):
    def test_each_builder(self):
        self.assertEqual(fr.category_of(REASON_WATCH), "watch")
        self.assertEqual(fr.category_of(REASON_LOOP), "loop-sleep")
        self.assertEqual(fr.category_of(REASON_SANDWICH), "sandwich")
        self.assertEqual(fr.category_of(REASON_SLEEP), "bare-sleep")
        self.assertEqual(fr.category_of(REASON_SLOW), "slow-timeout")
        self.assertEqual(fr.category_of(REASON_SLOW_TARGET), "slow-timeout")

    def test_backgrounded_class_a_keeps_its_category(self):
        # A poll run with run_in_background: true still prompts (issue #15),
        # with reworded reasons that must bucket the same way.
        self.assertEqual(fr.category_of(REASON_BG_WATCH), "watch")
        self.assertEqual(fr.category_of(REASON_BG_LOOP), "loop-sleep")
        self.assertEqual(fr.category_of(REASON_BG_SANDWICH), "sandwich")
        self.assertEqual(fr.category_of(REASON_BG_SLEEP), "bare-sleep")

    def test_signatures_mutually_exclusive(self):
        # No fixture reason matches more than one category signature.
        reasons = [REASON_WATCH, REASON_LOOP, REASON_SANDWICH, REASON_SLEEP,
                   REASON_SLOW, REASON_SLOW_TARGET, REASON_BG_WATCH,
                   REASON_BG_LOOP, REASON_BG_SANDWICH, REASON_BG_SLEEP]
        for reason in reasons:
            hits = [c for c, rx in fr.CATEGORY_PATTERNS.items()
                    if rx.search(reason)]
            self.assertEqual(len(hits), 1, "%r matched %s" % (reason, hits))

    def test_every_category_has_a_hint(self):
        for cat in fr.CATEGORY_PATTERNS:
            self.assertIn(cat, fr.CATEGORY_HINT)

    def test_unmatched_is_other(self):
        self.assertEqual(fr.category_of("foreground-guard: something new"),
                         "other")

    def test_override_keeps_underlying_category(self):
        # The override prefix does not change the underlying category.
        self.assertEqual(fr.category_of(REASON_OVERRIDE), "watch")


class TargetExtractionTests(unittest.TestCase):
    def test_watch_names_the_command(self):
        self.assertEqual(fr.named_target(REASON_WATCH), "gh run watch 456")
        self.assertEqual(fr.tool_of(REASON_WATCH), "gh")

    def test_slow_names_the_pattern(self):
        self.assertEqual(fr.named_target(REASON_SLOW), r"make test-race\b")
        self.assertEqual(fr.tool_of(REASON_SLOW), "make")

    def test_slow_target_form_names_the_target(self):
        self.assertEqual(fr.named_target(REASON_SLOW_TARGET), "make e2e*")
        self.assertEqual(fr.tool_of(REASON_SLOW_TARGET), "make")

    def test_template_categories_have_no_named_target(self):
        # loop/sandwich/bare-sleep lead with a generic template, not a command.
        for reason in (REASON_LOOP, REASON_SANDWICH, REASON_SLEEP):
            self.assertIsNone(fr.named_target(reason))
            self.assertIsNone(fr.tool_of(reason))


class DenyFromResultTests(unittest.TestCase):
    def _block(self, **kw):
        b = {"type": "tool_result", "tool_use_id": "toolu_1", "is_error": True,
             "content": REASON_DENY}
        b.update(kw)
        return b

    def test_recognizes_this_guard(self):
        got = fr.deny_from_result(self._block())
        self.assertEqual(got[0], "foreground-guard")
        self.assertEqual(got[1], REASON_DENY)

    def test_recognizes_a_sibling_guard(self):
        got = fr.deny_from_result(
            self._block(content="prod-guard: matches a production pattern"))
        self.assertEqual(got[0], "prod-guard")

    def test_error_prefix_tolerated(self):
        # The same text appears with an `Error: ` lead in some result shapes.
        got = fr.deny_from_result(self._block(content="Error: " + REASON_DENY))
        self.assertEqual(got[0], "foreground-guard")

    def test_content_as_text_blocks(self):
        got = fr.deny_from_result(
            self._block(content=[{"type": "text", "text": REASON_DENY}]))
        self.assertEqual(got[0], "foreground-guard")

    def test_successful_result_is_not_a_deny(self):
        self.assertIsNone(fr.deny_from_result(self._block(is_error=False)))
        self.assertIsNone(fr.deny_from_result(self._block(is_error=None)))

    def test_ordinary_failures_are_not_denies(self):
        for text in ("Exit code 1", "Exit code 143 Command timed out",
                     "The user doesn't want to proceed with this tool use.",
                     "Permission for this action was denied by the Claude Code "
                     "auto mode classifier"):
            self.assertIsNone(fr.deny_from_result(self._block(content=text)),
                              text)

    def test_reason_must_open_the_result(self):
        # A guard reason quoted mid-message is not this call's own verdict.
        self.assertIsNone(fr.deny_from_result(
            self._block(content="the tool failed: " + REASON_DENY)))

    def test_deny_tail_does_not_disturb_categorization(self):
        # The tail rides on the last segment and only ever appears on denies,
        # so it is the one reason text the category regexes never saw.
        self.assertEqual(fr.category_of(REASON_DENY), "loop-sleep")
        hits = [c for c, rx in fr.CATEGORY_PATTERNS.items()
                if rx.search(REASON_DENY)]
        self.assertEqual(hits, ["loop-sleep"])

    def test_deny_tail_does_not_invent_a_target(self):
        watch_deny = REASON_WATCH + " " + guard.deny_tail("auto")
        self.assertEqual(fr.named_target(watch_deny), "gh run watch 456")


class ErrorNoteTests(unittest.TestCase):
    def test_crash_names_code_and_first_stderr_line(self):
        note = fr.error_note({
            "type": "hook_non_blocking_error", "exitCode": 126,
            "stderr": "/bin/sh: run-python-hook.cmd: Permission denied\nmore"})
        self.assertEqual(
            note,
            "hook_non_blocking_error: exit 126: "
            "/bin/sh: run-python-hook.cmd: Permission denied")

    def test_timeout_without_an_exit_code(self):
        self.assertEqual(
            fr.error_note({"type": "hook_cancelled", "timedOut": True,
                           "timeoutMs": 600000}),
            "hook_cancelled: timed out after 600000ms")

    def test_bare_record_still_names_the_type(self):
        self.assertEqual(fr.error_note({"type": "hook_cancelled"}),
                         "hook_cancelled")
        self.assertEqual(fr.error_note({}), "unknown")

    def test_long_stderr_keeps_the_failure_at_the_end(self):
        # The path in the middle is what gets dropped, not the failure.
        note = fr.error_note({
            "type": "hook_non_blocking_error", "exitCode": 126,
            "stderr": "/bin/sh: " + "/very-long-path" * 20 +
                      "/run-python-hook.cmd: Permission denied"})
        self.assertTrue(note.endswith("Permission denied"), note)
        self.assertIn("/bin/sh:", note)
        self.assertEqual(len(note.split(": exit 126: ")[-1]), 120)

    def test_short_stderr_not_clipped(self):
        self.assertEqual(fr.clip("a b  c"), "a b c")
        self.assertNotIn("…", fr.clip("x" * 120))


class BuildReportTests(unittest.TestCase):
    def _report(self, decisions):
        return fr.build_report(decisions)

    def test_outcomes_and_friction(self):
        r = self._report([
            {"plugin": "foreground-guard", "decision": "ask", "reason": REASON_WATCH,
             "command": "gh run watch 456"},
            {"plugin": "foreground-guard", "decision": "ask", "reason": REASON_SLEEP,
             "command": "sleep 300"},
            {"plugin": "foreground-guard", "decision": "defer", "reason": "",
             "command": "gh run view 456"},
        ])
        self.assertEqual(r["total"], 3)
        self.assertEqual(r["decisions"]["ask"], 2)
        self.assertEqual(r["decisions"]["defer"], 1)
        self.assertEqual(r["categories"]["watch"], 1)
        self.assertEqual(r["categories"]["bare-sleep"], 1)

    def test_named_target_and_tool_ranked(self):
        r = self._report([
            {"plugin": "foreground-guard", "decision": "ask", "reason": REASON_WATCH,
             "command": "gh run watch 456"},
            {"plugin": "foreground-guard", "decision": "ask", "reason": REASON_SLOW,
             "command": "make test-race"},
        ])
        self.assertEqual(r["targets"]["gh run watch 456"], 1)
        self.assertEqual(r["targets"][r"make test-race\b"], 1)
        self.assertEqual(r["tools"]["gh"], 1)
        self.assertEqual(r["tools"]["make"], 1)

    def test_template_category_has_no_target_but_ranks_command(self):
        r = self._report([
            {"plugin": "foreground-guard", "decision": "ask", "reason": REASON_LOOP,
             "command": "while true; do gh pr checks 1; sleep 5; done"},
        ])
        self.assertEqual(r["categories"]["loop-sleep"], 1)
        self.assertEqual(len(r["targets"]), 0)
        self.assertEqual(
            r["commands"]["while true; do gh pr checks 1; sleep 5; done"], 1)

    def test_override_counted(self):
        r = self._report([
            {"plugin": "foreground-guard", "decision": "ask", "reason": REASON_OVERRIDE,
             "command": "FOREGROUND_GUARD_OVERRIDE=x gh run watch 456"},
        ])
        self.assertEqual(r["overrides"], 1)
        self.assertEqual(r["decisions"]["ask"], 1)
        self.assertEqual(r["categories"]["watch"], 1)

    def test_sibling_guard_override_not_counted(self):
        r = self._report([
            {"plugin": "prod-guard", "decision": "deny",
             "reason": REASON_SIBLING_OVERRIDE,
             "command": "PROD_GUARD_OVERRIDE=x kubectl delete ns x"},
            {"plugin": "foreground-guard", "decision": "ask",
             "reason": REASON_OVERRIDE,
             "command": "FOREGROUND_GUARD_OVERRIDE=x gh run watch 456"},
        ])
        self.assertEqual(r["overrides"], 1)

    def test_error_is_counted_apart_from_friction(self):
        r = self._report([
            {"plugin": "pipe-guard", "decision": "error",
             "reason": "hook_non_blocking_error: exit 126: Permission denied",
             "command": "git status"},
            {"plugin": "foreground-guard", "decision": "ask",
             "reason": REASON_WATCH, "command": "gh run watch 456"},
        ])
        self.assertEqual(r["decisions"]["error"], 1)
        self.assertEqual(r["decisions"].get("defer", 0), 0)
        self.assertEqual(
            r["errors"]["pipe-guard: hook_non_blocking_error: exit 126: "
                        "Permission denied"], 1)
        # It is not a prompt, so it reaches no ranking that maps to a fix.
        self.assertEqual(sum(r["categories"].values()), 1)
        self.assertEqual(list(r["commands"]), ["gh run watch 456"])

    def test_joined_reason_hits_both_categories(self):
        joined = REASON_WATCH + " | " + REASON_SLEEP
        r = self._report([
            {"plugin": "foreground-guard", "decision": "ask", "reason": joined,
             "command": "gh run watch 456; sleep 300"},
        ])
        self.assertEqual(r["categories"]["watch"], 1)
        self.assertEqual(r["categories"]["bare-sleep"], 1)


class IterDecisionsTests(unittest.TestCase):
    def test_join_and_filter(self):
        use1, att1 = _decision_record(
            "toolu_1", "gh run watch 456", _stdout("ask", REASON_WATCH))
        # A prod-guard decision that must be excluded by --plugin foreground-guard.
        use2, att2 = _decision_record(
            "toolu_2", "kubectl delete ns x",
            _stdout("deny", "prod-guard: matches a production pattern ..."),
            hook_cmd='python3 "/x/bash-prod-guard.py"')
        root = write_transcript([use1, att1, use2, att2])
        paths = [str(p) for p in Path(root).rglob("*.jsonl")]

        got = list(fr.iter_decisions(paths, "foreground-guard", None, ""))
        self.assertEqual(len(got), 1)
        self.assertEqual(got[0]["decision"], "ask")
        self.assertEqual(got[0]["command"], "gh run watch 456")

        # --plugin all sees both.
        self.assertEqual(len(list(fr.iter_decisions(paths, "all", None, ""))), 2)

    def test_repo_filter(self):
        use, att = _decision_record(
            "toolu_1", "gh run watch 456", _stdout("ask", REASON_WATCH),
            cwd="/home/u/gateway")
        root = write_transcript([use, att])
        paths = [str(p) for p in Path(root).rglob("*.jsonl")]
        self.assertEqual(len(list(fr.iter_decisions(paths, "foreground-guard", None, "gateway"))), 1)
        self.assertEqual(len(list(fr.iter_decisions(paths, "foreground-guard", None, "nope"))), 0)

    def test_cutoff_filter(self):
        use, att = _decision_record(
            "toolu_1", "gh run watch 456", _stdout("ask", REASON_WATCH),
            ts="2020-01-01T00:00:00Z")
        root = write_transcript([use, att])
        paths = [str(p) for p in Path(root).rglob("*.jsonl")]
        cutoff = dt.datetime(2025, 1, 1, tzinfo=dt.timezone.utc)
        self.assertEqual(len(list(fr.iter_decisions(paths, "foreground-guard", cutoff, ""))), 0)

    def test_defer_recorded_for_empty_stdout_on_success(self):
        # An empty stdout on a hook that *ran* is the one genuinely ambiguous
        # record (one in 66,223 locally); reading it as a defer is fine. The
        # type is what makes it distinguishable from the crashes below.
        use, att = _decision_record("toolu_1", "gh run view 456", "")
        root = write_transcript([use, att])
        paths = [str(p) for p in Path(root).rglob("*.jsonl")]
        got = list(fr.iter_decisions(paths, "foreground-guard", None, ""))
        self.assertEqual(len(got), 1)
        self.assertEqual(got[0]["decision"], "defer")

    def test_crashed_hook_is_an_error_not_a_defer(self):
        # Issue #29: a defer means the guard looked and let the call through; a
        # 126 means it was never consulted, so the call went unguarded.
        use, att = _crashed_record("toolu_1", "git status",
                                   'python3 "/x/bash-foreground-guard.py"')
        root = write_transcript([use, att])
        paths = [str(p) for p in Path(root).rglob("*.jsonl")]
        got = list(fr.iter_decisions(paths, "foreground-guard", None, ""))
        self.assertEqual([d["decision"] for d in got], ["error"])
        self.assertIn("exit 126", got[0]["reason"])
        self.assertIn("Permission denied", got[0]["reason"])

    def test_cancelled_hook_is_an_error(self):
        # A cancelled hook carries neither exitCode nor stderr — only the
        # timeout — so the note has to be built from whatever the record has.
        use, att = _decision_record(
            "toolu_1", "git status", "",
            hook_cmd='python3 "/x/bash-foreground-guard.py"',
            type="hook_cancelled", exitCode=None, stderr=None,
            timedOut=True, timeoutMs=600000)
        root = write_transcript([use, att])
        paths = [str(p) for p in Path(root).rglob("*.jsonl")]
        got = list(fr.iter_decisions(paths, "foreground-guard", None, ""))
        self.assertEqual([d["decision"] for d in got], ["error"])
        self.assertEqual(got[0]["reason"],
                         "hook_cancelled: timed out after 600000ms")

    def test_crashed_hook_does_not_mark_the_session_prompted(self):
        use, att = _crashed_record("toolu_1", "git status",
                                   'python3 "/x/bash-foreground-guard.py"')
        root = write_transcript([use, att])
        paths = [str(p) for p in Path(root).rglob("*.jsonl")]
        tally = fr.new_scope()
        list(fr.iter_decisions(paths, "foreground-guard", None, "", tally))
        self.assertEqual(tally["sessions_prompted"], 0)
        self.assertEqual(tally["bash_calls"], 1)

    def test_deny_recovered_from_the_tool_result(self):
        # The whole point of issue #25: no attachment, and the decision must
        # still land — with its command joined.
        use, result = _deny_record(
            "toolu_1", "while :; do gh pr checks 1; sleep 5; done")
        root = write_transcript([use, result])
        paths = [str(p) for p in Path(root).rglob("*.jsonl")]
        got = list(fr.iter_decisions(paths, "foreground-guard", None, ""))
        self.assertEqual(len(got), 1)
        self.assertEqual(got[0]["decision"], "deny")
        self.assertEqual(got[0]["command"],
                         "while :; do gh pr checks 1; sleep 5; done")
        self.assertEqual(got[0]["reason"], REASON_DENY)

    def test_deny_honors_plugin_and_scope_filters(self):
        use1, res1 = _deny_record("toolu_1", "sleep 300",
                                  reason="prod-guard: production pattern")
        use2, res2 = _deny_record("toolu_2", "sleep 400", cwd="/home/u/gateway")
        use3, res3 = _deny_record("toolu_3", "sleep 500",
                                  ts="2020-01-01T00:00:00Z")
        root = write_transcript([use1, res1, use2, res2, use3, res3])
        paths = [str(p) for p in Path(root).rglob("*.jsonl")]

        ours = list(fr.iter_decisions(paths, "foreground-guard", None, ""))
        self.assertEqual([d["command"] for d in ours], ["sleep 400", "sleep 500"])
        self.assertEqual(len(list(fr.iter_decisions(paths, "all", None, ""))), 3)
        self.assertEqual(
            [d["command"] for d in
             fr.iter_decisions(paths, "foreground-guard", None, "gateway")],
            ["sleep 400"])
        cutoff = dt.datetime(2025, 1, 1, tzinfo=dt.timezone.utc)
        self.assertEqual(
            [d["command"] for d in
             fr.iter_decisions(paths, "foreground-guard", cutoff, "")],
            ["sleep 400"])

    def test_deny_not_double_counted_with_an_attachment(self):
        # Defensive: a call this guard already decided in the attachment stream
        # is counted once, whatever text its result carries.
        use, att = _decision_record(
            "toolu_1", "gh run watch 456", _stdout("ask", REASON_WATCH))
        _, result = _deny_record("toolu_1", "gh run watch 456")
        root = write_transcript([use, att, result])
        paths = [str(p) for p in Path(root).rglob("*.jsonl")]
        got = list(fr.iter_decisions(paths, "foreground-guard", None, ""))
        self.assertEqual([d["decision"] for d in got], ["ask"])

    def test_deny_on_a_non_bash_call_ignored(self):
        # A sibling guard blocking an Edit has no Bash tool_use to join to, and
        # does not belong in a PreToolUse:Bash report.
        _, result = _deny_record("toolu_edit", "unused",
                                 reason="workspace-guard: outside the workspace")
        root = write_transcript([result])
        paths = [str(p) for p in Path(root).rglob("*.jsonl")]
        self.assertEqual(len(list(fr.iter_decisions(paths, "all", None, ""))), 0)

    def test_malformed_line_skipped(self):
        root = tempfile.mkdtemp(prefix="fg-guard-friction-bad-")
        with open(os.path.join(root, "s.jsonl"), "w", encoding="utf-8") as f:
            f.write("{not json\n")
            use, att = _decision_record(
                "toolu_1", "gh run watch 456", _stdout("ask", REASON_WATCH))
            f.write(json.dumps(use) + "\n")
            f.write(json.dumps(att) + "\n")
        paths = [os.path.join(root, "s.jsonl")]
        self.assertEqual(len(list(fr.iter_decisions(paths, "foreground-guard", None, ""))), 1)


class ScopeTallyTests(unittest.TestCase):
    """The denominator (issue #27). The guard prints nothing when it defers, so
    a share of its own decision records is 100% by construction; the rate has to
    divide by Bash calls, which the transcript records whatever a hook decided."""

    def _tally(self, sessions, plugin="foreground-guard", cutoff=None, repo=""):
        root = write_transcripts(sessions)
        paths = [str(p) for p in Path(root).rglob("*.jsonl")]
        tally = fr.new_scope()
        decisions = list(fr.iter_decisions(paths, plugin, cutoff, repo, tally))
        return tally, decisions

    def _prompt_and_defers(self, n_defers, cwd="/home/u/proj", ts=None):
        use, att = _decision_record("toolu_p", "gh run watch 456",
                                    _stdout("ask", REASON_WATCH), cwd=cwd, ts=ts)
        quiet = [_bash_call("toolu_q%d" % i, "git status", cwd=cwd, ts=ts)
                 for i in range(n_defers)]
        return [use, att] + quiet

    def test_silent_defers_reach_the_denominator(self):
        tally, decisions = self._tally([self._prompt_and_defers(3)])
        # One prompt recorded, four Bash calls made.
        self.assertEqual(len(decisions), 1)
        self.assertEqual(tally["bash_calls"], 4)
        self.assertEqual(tally["sessions"], 1)
        self.assertEqual(tally["sessions_prompted"], 1)

    def test_quiet_session_counts_but_does_not_prompt(self):
        tally, _ = self._tally([
            self._prompt_and_defers(1),
            [_bash_call("toolu_x", "git status")],
        ])
        self.assertEqual(tally["sessions"], 2)
        self.assertEqual(tally["sessions_prompted"], 1)
        self.assertEqual(tally["bash_calls"], 3)

    def test_repo_filter_scopes_the_denominator(self):
        sessions = [self._prompt_and_defers(2),
                    self._prompt_and_defers(4, cwd="/home/u/gateway")]
        tally, _ = self._tally(sessions, repo="gateway")
        self.assertEqual(tally["bash_calls"], 5)
        self.assertEqual(tally["sessions"], 1)

    def test_cutoff_scopes_the_denominator(self):
        sessions = [self._prompt_and_defers(2),
                    self._prompt_and_defers(4, ts="2020-01-01T00:00:00Z")]
        cutoff = dt.datetime(2025, 1, 1, tzinfo=dt.timezone.utc)
        tally, _ = self._tally(sessions, cutoff=cutoff)
        self.assertEqual(tally["bash_calls"], 3)
        self.assertEqual(tally["sessions"], 1)

    def test_denominator_does_not_depend_on_the_plugin_filter(self):
        # A Bash call belongs to no guard, so --plugin only moves the numerator.
        session = self._prompt_and_defers(2)
        use, att = _decision_record(
            "toolu_s", "kubectl delete ns x",
            _stdout("ask", "prod-guard: matches a production pattern"),
            hook_cmd='python3 "/x/bash-prod-guard.py"')
        session += [use, att]
        ours, mine = self._tally([session])
        theirs, all_ = self._tally([session], plugin="all")
        self.assertEqual(ours["bash_calls"], theirs["bash_calls"])
        self.assertEqual([len(mine), len(all_)], [1, 2])

    def test_deny_marks_the_session_prompted(self):
        # A deny reaches the report through the tool result, not an attachment;
        # the session still has to count as one this guard interrupted.
        use, res = _deny_record("toolu_1", "sleep 300")
        tally, _ = self._tally([[use, res, _bash_call("toolu_2", "git status")]])
        self.assertEqual(tally["sessions_prompted"], 1)
        self.assertEqual(tally["bash_calls"], 2)


class PrintTests(unittest.TestCase):
    def test_empty(self):
        buf = io.StringIO()
        with redirect_stdout(buf):
            fr.print_text(fr.build_report([]), 15)
        self.assertIn("No foreground-guard decisions", buf.getvalue())

    def test_sections_present(self):
        r = fr.build_report([
            {"plugin": "foreground-guard", "decision": "ask", "reason": REASON_WATCH,
             "command": "gh run watch 456"},
        ])
        buf = io.StringIO()
        with redirect_stdout(buf):
            fr.print_text(r, 15)
        out = buf.getvalue()
        self.assertIn("decisions recorded: 1", out)
        self.assertIn("By category", out)
        self.assertIn("watch", out)
        self.assertIn("gh run watch 456", out)

    def test_rate_omitted_without_a_denominator(self):
        # No tally: the count prints alone rather than borrowing the decision
        # records as a denominator, which is what made it always 100%.
        r = fr.build_report([
            {"plugin": "foreground-guard", "decision": "ask", "reason": REASON_WATCH,
             "command": "gh run watch 456"},
        ])
        buf = io.StringIO()
        with redirect_stdout(buf):
            fr.print_text(r, 15)
        out = buf.getvalue()
        self.assertIn("friction (ask+deny): 1\n", out)
        self.assertNotIn("%", out)

    def test_rate_is_the_share_of_bash_calls(self):
        r = fr.build_report(
            [{"plugin": "foreground-guard", "decision": "ask",
              "reason": REASON_WATCH, "command": "gh run watch 456"}],
            {"bash_calls": 20, "sessions": 4, "sessions_prompted": 1})
        buf = io.StringIO()
        with redirect_stdout(buf):
            fr.print_text(r, 15)
        out = buf.getvalue()
        self.assertIn("friction (ask+deny): 1 — 5.0% of the 20 Bash calls", out)
        self.assertIn("sessions with a prompt: 1 of 4 (25%)", out)

    def test_hook_failures_section(self):
        r = fr.build_report([
            {"plugin": "pipe-guard", "decision": "error",
             "reason": "hook_non_blocking_error: exit 126: Permission denied",
             "command": "git status"},
        ])
        buf = io.StringIO()
        with redirect_stdout(buf):
            fr.print_text(r, 15, "all")
        out = buf.getvalue()
        self.assertIn("Hook failures", out)
        self.assertIn("pipe-guard: hook_non_blocking_error: exit 126", out)
        self.assertIn("error 1", out)
        self.assertNotIn("defer", out)

    def test_hook_failures_section_omitted_when_clean(self):
        r = fr.build_report([
            {"plugin": "foreground-guard", "decision": "ask",
             "reason": REASON_WATCH, "command": "gh run watch 456"},
        ])
        buf = io.StringIO()
        with redirect_stdout(buf):
            fr.print_text(r, 15)
        self.assertNotIn("Hook failures", buf.getvalue())

    def test_override_line_shown_for_this_guard(self):
        r = fr.build_report([
            {"plugin": "foreground-guard", "decision": "ask",
             "reason": REASON_OVERRIDE, "command": "gh run watch 456"},
        ])
        buf = io.StringIO()
        with redirect_stdout(buf):
            fr.print_text(r, 15)
        self.assertIn("FOREGROUND_GUARD_OVERRIDE downgrades: 1", buf.getvalue())

    def test_override_line_omitted_under_plugin_all(self):
        r = fr.build_report([
            {"plugin": "foreground-guard", "decision": "ask",
             "reason": REASON_OVERRIDE, "command": "gh run watch 456"},
        ])
        buf = io.StringIO()
        with redirect_stdout(buf):
            fr.print_text(r, 15, "all")
        self.assertNotIn("FOREGROUND_GUARD_OVERRIDE", buf.getvalue())


class EndToEndTests(unittest.TestCase):
    def _run(self, root, *args):
        r = subprocess.run(
            [sys.executable, str(SCRIPT), "--transcripts", root,
             "--since", "all", *args],
            capture_output=True, text=True, timeout=30)
        self.assertEqual(r.returncode, 0, r.stderr)
        return r.stdout

    def test_text_report(self):
        use, att = _decision_record(
            "toolu_1", "gh run watch 456", _stdout("ask", REASON_WATCH))
        root = write_transcript([use, att])
        out = self._run(root)
        self.assertIn("foreground-guard decisions recorded: 1", out)
        self.assertIn("watch", out)
        self.assertIn("gh run watch 456", out)

    def test_json_report(self):
        use, att = _decision_record(
            "toolu_1", "make test-race", _stdout("ask", REASON_SLOW))
        root = write_transcript([use, att])
        out = self._run(root, "--json")
        data = json.loads(out)
        self.assertEqual(data["total"], 1)
        self.assertEqual(data["decisions"]["ask"], 1)
        self.assertEqual(data["categories"]["slow-timeout"], 1)
        self.assertEqual(data["tools"]["make"], 1)

    def test_sibling_override_never_reported_as_ours(self):
        use1, att1 = _decision_record(
            "toolu_1", "gh run watch 456", _stdout("ask", REASON_WATCH))
        use2, att2 = _decision_record(
            "toolu_2", "kubectl delete ns x",
            _stdout("ask", REASON_SIBLING_OVERRIDE),
            hook_cmd='python3 "/x/bash-prod-guard.py"')
        root = write_transcript([use1, att1, use2, att2])

        # This guard's own report: the sibling's override is not ours.
        self.assertEqual(json.loads(self._run(root, "--json"))["overrides"], 0)

        # --plugin all: both decisions in scope, no override count at all.
        data = json.loads(self._run(root, "--plugin", "all", "--json"))
        self.assertEqual(data["total"], 2)
        self.assertNotIn("overrides", data)
        out = self._run(root, "--plugin", "all")
        self.assertIn("guard decisions recorded: 2", out)
        self.assertNotIn("FOREGROUND_GUARD_OVERRIDE", out)

    def test_denying_guard_reports_its_friction(self):
        # An unattended-mode session: every prompt became a deny, so the
        # attachment stream holds nothing but the defers. Before the recovery
        # this reported 0% friction.
        use1, res1 = _deny_record("toolu_1", "sleep 300")
        use2, att2 = _decision_record("toolu_2", "gh run view 456", "")
        root = write_transcript([use1, res1, use2, att2])

        data = json.loads(self._run(root, "--json"))
        self.assertEqual(data["total"], 2)
        self.assertEqual(data["decisions"]["deny"], 1)
        self.assertEqual(data["categories"]["loop-sleep"], 1)

        out = self._run(root)
        self.assertIn("deny 1", out)
        self.assertIn("friction (ask+deny): 1 — 50.0% of the 2 Bash calls", out)
        self.assertIn("loop-sleep", out)
        self.assertIn("sleep 300", out)
        # The caveat belongs to the cross-guard view only.
        self.assertNotIn("tool-result text", out)

    def test_plugin_all_states_the_recovery_limit(self):
        use, res = _deny_record("toolu_1", "sleep 300")
        root = write_transcript([use, res])
        self.assertIn("tool-result text", self._run(root, "--plugin", "all"))

    def test_friction_rate_falls_when_the_guard_stays_quiet(self):
        # The issue #27 regression: before the denominator moved to Bash calls
        # this read 100%, and went on reading 100% however quiet the guard got.
        use, att = _decision_record(
            "toolu_1", "gh run watch 456", _stdout("ask", REASON_WATCH))
        quiet = [_bash_call("toolu_q%d" % i, "git status") for i in range(9)]
        root = write_transcripts([[use, att] + quiet])

        out = self._run(root)
        self.assertIn("friction (ask+deny): 1 — 10.0% of the 10 Bash calls", out)
        self.assertIn("sessions with a prompt: 1 of 1", out)

        data = json.loads(self._run(root, "--json"))
        self.assertEqual(data["total"], 1)          # decision records, as before
        self.assertEqual(data["bash_calls"], 10)
        self.assertEqual(data["sessions"], 1)
        self.assertEqual(data["sessions_prompted"], 1)

    def test_plugin_all_reports_a_sibling_that_stopped_running(self):
        # The blast radius of issue #29: under --plugin all a sibling whose hook
        # crashed on every call was reported as `defer`, reading as a guard that
        # looked and allowed rather than one that was never consulted.
        use1, att1 = _crashed_record("toolu_1", "git status",
                                     'python3 "/x/bash-pipe-guard.py"')
        use2, att2 = _decision_record(
            "toolu_2", "gh run watch 456", _stdout("ask", REASON_WATCH))
        root = write_transcript([use1, att1, use2, att2])

        data = json.loads(self._run(root, "--plugin", "all", "--json"))
        self.assertEqual(data["decisions"]["error"], 1)
        self.assertNotIn("defer", data["decisions"])
        self.assertEqual(
            data["hook_errors"],
            [["pipe-guard: hook_non_blocking_error: exit 126: Failed with "
              "non-blocking status code: /bin/sh: /x/scripts/"
              "run-python-hook.cmd: Permission denied", 1]])

        out = self._run(root, "--plugin", "all")
        self.assertIn("Hook failures", out)
        self.assertIn("pipe-guard: hook_non_blocking_error: exit 126", out)
        # The crash is not friction: it neither prompted nor let the guard look.
        self.assertIn("friction (ask+deny): 1 — 50.0% of the 2 Bash calls", out)

    def test_no_transcripts_errors(self):
        empty = tempfile.mkdtemp(prefix="fg-guard-friction-empty-")
        r = subprocess.run(
            [sys.executable, str(SCRIPT), "--transcripts", empty],
            capture_output=True, text=True, timeout=30)
        self.assertNotEqual(r.returncode, 0)
        self.assertIn("No transcripts", r.stderr)


if __name__ == "__main__":
    unittest.main()
